config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :docs
  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end
  
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :docs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]
  
  def index
    # @docs = current_user.docs.order("created_at desc") # alternative 1.
    @docs = Doc.where(user_id: current_user)             # alternative 2.
  end
  
  def show
  end
  
  def new
    # @doc = Doc.new
    @doc = current_user.docs.build
  end
  
  def create
    @doc = current_user.docs.build(doc_params)
    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render 'edit'
    end
  end
  
  def destroy
    @doc.destroy
    redirect_to docs_path
  end
  
  private
  
  def find_doc
    @doc = Doc.find(params[:id])
  end
  
  def doc_params
    params.require(:doc).permit(:title, :content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
  = f.input   :title
  = f.input   :content
  = f.button  :submit

app/views/docs/edit.html.haml
%h1 New doc
= render 'form'

app/views/docs/index.html.haml
.wrapper_with_padding
  #docs.clearfix
    - unless @docs.blank?
      - @docs.each do |doc|
        %a{ href: (url_for [doc])}
          .doc
            %p.title= doc.title
            %p.date= time_ago_in_words(doc.created_at)
            %p.content= truncate(doc.content, length: 50)
    - else
      %h2 Create Doc!
      %p Start creating documents.
      %button= link_to "Create doc", new_doc_path

app/views/docs/new.html.haml
%h1 New doc
= render 'form'

app/views/docs/show.html.haml
%h1= @doc.title
%p= @doc.content

= link_to "All docs", docs_path
= link_to "Edit", edit_doc_path(@doc)
= link_to "Delete", doc_path(@doc), method: :delete, data: { confirm: "Are you sure?" }

app/views/layouts/application.html.haml
!!!
%html
%head
  %title "FileCabinet"
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = csrf_meta_tags
    
  %body
    %header
      .header_inner
        = link_to "FileCabinet", root_path, id: :logo
        
        %nav
          - if user_signed_in?
            = link_to "Created doc", new_doc_path
            = link_to "Sign Out", destroy_user_session_path, method: :delete
          - else
            = link_to "Log in", new_user_session_path
    
    %p.notice= notice
    %p.alert= alert
    
    = yield

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 File Cabinet
    %p Your life's work.
    %button= link_to "Sign up", new_user_registration_path

#callouts
  .callout_inner
    .wrapper
      .callout
        %h2 Organize
        %p Plaid whatever keytar chartreuse etsy, fashion axe brunch jianbing farm-to-table. Taxidermy letterpress shoreditch intelligentsia viral venmo. Taiyaki coloring book edison bulb direct trade selfies kogi succulents flexitarian shaman pok pok single-origin coffee meditation heirloom iPhone disrupt. Banjo swag microdosing woke.
        
#button_cta
  .wrapper
    %h2 Go ahead!
    %br
    %button= link_to "Join now!"
    